---
# Install and setup PostgreSQL with Streaming Replication
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
  tasks:
  - include: 'tasks/install.yml'

- hosts: pgmaster
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - group_by: key=os_{{ ansible_os_family }}
  - include: 'tasks/install_supervisor.yml'
  - include: 'tasks/configure-master.yml'
  - include: 'tasks/users.yml'
  - include: 'tasks/databases.yml'
  - include: 'tasks/pglogical-master.yml'

- hosts: pgslave
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - group_by: key=os_{{ ansible_os_family }}
  - include: 'tasks/install_supervisor.yml'
  - include: 'tasks/configure-slaves.yml'
  - include: 'tasks/pglogical-slave.yml'

